### ISSUE TITLE
finetuning on custom dataset?

### ISSUE THREAD

**Issue by mureva** [liuyuan-pal/NeuRay#14]
Hi,

I've run the general algorithm on some custom data - it does quite a nice job on my relatively sparse views vs the few other tools I've been trialling - is it possible to run fine-tuning on custom data to further improve the performance? I'm not quite sure I understand how the configs should be adapted.

**Comment by liuyuan-pal** [comment]
Thanks for your advice! I've updated codes to finetune on custom scenes, the commands can be found at
https://github.com/liuyuan-pal/NeuRay/blob/main/custom_rendering.md#finetuning-on-a-custom-scene
