### ISSUE TITLE
What's the difference between configs/gen/neuray_gen_cost_volume.yaml and configs/train/gen/neuray_gen_cost_volume_train.yaml?

### ISSUE THREAD

**Issue by EchoTHChen** [liuyuan-pal/NeuRay#21]
This is a great work! But I still have a question. Why does `train/ft/neuray_ft_cv_lego.yaml` use neuray_gen_cost_volume.yaml as the pretrained model setting instead of `configs/train/gen/neuray_gen_cost_volume_train.yaml`?

**Comment by liuyuan-pal** [comment]
Hi, they actually are the same, I just use one for training and one for the pre-trained model. The fine-tuning code is an example of how to fine-tune on a scene so I use the pretrain model for the example.

**Comment by EchoTHChen** [comment]
Thanks
