### ISSUE TITLE
An error about inplace-abn

### ISSUE THREAD

**Issue by ZYY-666** [liuyuan-pal/NeuRay#3]
Hello, after I configured the environment, I encountered the following error when running your test code.
Do you know what the reason is?
![image](https://user-images.githubusercontent.com/69071467/161540640-6eae8288-f644-469c-a18d-356fd3280332.png)

**Comment by liuyuan-pal** [comment]
Hi, the reason may be that the cpython.so you used in the compilation is different from the one you load in the program. (I'm not sure about this.) You may try to manually compile this inplace_abn module instead of using pip for installation.

Alternatively, this inplace_abn is only used in the cost volume-based pretrained model so you may just delete this import line if you only use the depth-based pretrained model.

**Comment by ZYY-666** [comment]
Thanks for your reply. As you said, after I compiled inplace_abn module manually, the code ran successfully. Thank you very much！
I would like to ask one more question, why the manual compilation way can be successful, but using pip to install is not?  I've been under the misconception that they are equivalent operations.

**Comment by ZYY-666** [comment]
> Hi, the reason may be that the cpython.so you used in the compilation is different from the one you load in the program. (I'm not sure about this.) You may try to manually compile this inplace_abn module instead of using pip for installation.
> 
> Alternatively, this inplace_abn is only used in the cost volume-based pretrained model so you may just delete this import line if you only use the depth-based pretrained model.
Thanks for your reply. As you said, after I compiled inplace_abn module manually, the code ran successfully.

**Comment by ZYY-666** [comment]
As you said, after I compiled inplace_abn module manually, the code ran successfully.&nbsp;Thanks very much for your help.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuyuan-pal/NeuRay"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月5日(星期二) 中午11:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuyuan-pal/NeuRay] An error about inplace-abn (Issue #3)





 
Hi, the reason may be that the cpython.so you used in the compilation is different from the one you load in the program. (I'm not sure about this.) You may try to manually compile this file.
 
Alternatively, this inplace_abn is only used in the cost volume-based pretrained model so you may just delete this import line if you only use the depth-based pretrained model.

**Comment by liuyuan-pal** [comment]
> 

I'm not sure about how "pip install" compile the module, it may include some unwanted .so files for linking, which causes your problem.

**Comment by ZYY-666** [comment]
Hello, I would like to ask, if I use your code to train my own scenes, then when making datasets, can the depth map not be provided?&nbsp;In other words, if I only have images of the scene and the camera's internal and external parameters, can I train the model?
