### ISSUE TITLE
Cannot download the pre-training model

### ISSUE THREAD

**Issue by racso10** [liuyuan-pal/NeuRay#31]
Hi, the Google Drive link for the pre-trained model is down. Could you please update the link?
Thanks!

**Comment by liuyuan-pal** [comment]
Oh, it seems that HKU stops the services on the google drive. I'll update the link this weekend.

**Comment by liuyuan-pal** [comment]
Hi, the pretrained models are back now

**Comment by racso10** [comment]
Thanks~
