### ISSUE TITLE
is there a reason why run colmap patch_match_stereo for twice at colmap_scripts/process.py line 73

### ISSUE THREAD

**Issue by guijuzhejiang** [liuyuan-pal/NeuRay#8]
colmap_scripts/process.py:
cmd=[colmap_path,'patch_match_stereo',
     '--workspace_path',f'{project_dir}/dense']
print(' '.join(cmd))
subprocess.run(cmd,check=True)

cmd=[colmap_path,'patch_match_stereo',
     '--workspace_path',f'{project_dir}/dense']
print(' '.join(cmd))
subprocess.run(cmd,check=True)

**Comment by liuyuan-pal** [comment]
Sorry, I've made a mistake here to repeat this piece of code twice. Thanks for the reminder and I'll fix it.
